// Site auth configuration — empty hash disables the site password gate
// Generated by automation to disable password protection for the site.
window.SITE_PASSWORD_HASH = '';
// Generated by set_site_password.sh — do not commit this file with a real secret if you need privacy.
window.SITE_PASSWORD_HASH = '9f1de0fd544db906ecc9fd6ed12fcf6997354fa147bdb5bd4186e8be88652245';
