#!/usr/bin/env bash
# Helper to set the site password by writing a SHA-256 hash into js/auth-config.js
# Usage: ./set_site_password.sh

read -s -p "Enter new site password: " PW
echo
if [ -z "$PW" ]; then
  echo "Empty password, aborting. To disable the gate leave js/auth-config.js SITE_PASSWORD_HASH empty."; exit 1; fi
HASH=$(printf "%s" "$PW" | shasum -a 256 | awk '{print $1}')
cat > js/auth-config.js <<EOF
// Generated by set_site_password.sh — do not commit this file with a real secret if you need privacy.
window.SITE_PASSWORD_HASH = '$HASH';
EOF
chmod 600 js/auth-config.js
echo "Wrote js/auth-config.js with password hash (SHA-256)."
